id: IBE63CE3C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:48:11+00:00'
last_modified: '2022-06-09T05:19:17.582859+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4716
  title: འདུལ་བ་མདོ་རྩའི་རྣམ་བཤད་སློབ་དཔོན་ཡོན་ཏན་འོད་ཀྱི་དགོངས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AB8E:
      image_group_id: I3CN4718
      title: ''
      total_pages: 590
      order: 1
      base_file: AB8E.txt
    4D28:
      image_group_id: I3CN4719
      title: ''
      total_pages: 648
      order: 2
      base_file: 4D28.txt
    498A:
      image_group_id: I3CN4720
      title: ''
      total_pages: 682
      order: 3
      base_file: 498A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
