id: IBE63CE3C
legacy_id: P008218
ocr_import_info:
  bdrc_scan_id: W3CN4716
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T21:43:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:38:44.516948+00:00'
last_modified: 2022-08-27 19:40:38.056029
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4716
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4716
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བ་མདོ་རྩའི་རྣམ་བཤད་སློབ་དཔོན་ཡོན་ཏན་འོད་ཀྱི་དགོངས་རྒྱན།
  author: མཁན་པོ་རིག་འཛིན་དར་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.9572059102168122
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN4718:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4718
      total_pages: 590
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4718.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9644664001623043
    legacy_id: v001
  I3CN4720:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4720
      total_pages: 682
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN4720.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9535763921317004
    legacy_id: v003
  I3CN4719:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4719
      total_pages: 648
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN4719.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9546172958340123
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
